### PR TITLE
Fixed: Invisible horizontal rules

### PR DESCRIPTION
**Pull request by evanwon**
Hey Nicolas,

Github uses images for horizontal rules, but this style doesn't include the image so the horizontal rule is not visible. I just removed the horizontal rule styling which fixes the problem, but I'm definitely open to other solutions.

Thanks!

Evan

### CODE REVIEW

**Comment by nicolashery** [comment]
Hey Evan,

Good catch! Indeed they have a pretty fancy style for a simple `<hr>` (test below) :)

Either we can leave the default browser `<hr>` style by removing the rule like you did. Or we could try to "emulate" GitHub's with something like:

``` css
.hr {
  clear: both;
  margin: 15px 0;
  height: 0px;
  overflow: hidden;
  border: none;
  background: transparent;
  border-bottom: 4px dotted #ddd;
  /* or:
  border-bottom: 4px solid #ddd;
  */
  padding: 0;
}
```

I'll let you play around with it?

Testing GitHub `<hr>`:

---

Cheers
Nicolas

**Comment by evanwon** [comment]
Very nice, although there's a little bit of dotted line weirdness on both ends of the style (I also had to remove the `.` in front of the hr as it's not referring to a class).



I'm a bit torn on what to do here. I actually hadn't noticed GitHub's striped horizontal rule until just recently, and it surprised me a bit in that it seems to not entirely match the rest of the visual theme. I feel inclined just to use the browser default, but that's pretty boring as well.

Although, I just tried out the solid version of your updated horizontal rule, and I do find myself liking it a lot ... What do you think?

**Comment by nicolashery** [comment]
Yeah I also saw that there was some weird thing going on at the tip when I tested the dotted line.

I agree with you, I'm not a fan of GitHub's "slanted dotted line" thing for `<hr>`, looks almost like a thin progress bar not moving.

I do find the 4px solid light grey `<hr>` elegant, and less boring than the browser default :) So you have my approval on that one if you choose to use it!

Would you mind sending another pull request so I can merge it in this repo as well?

Thanks!
Nicolas

**Comment by evanwon** [comment]
Added a new commit to the existing pull request. Let me know if that works for you.

**Comment by nicolashery** [comment]
That's perfect. Thanks!

**Pull request merged**
